# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Albert Au Yeung'
tagline:          'Notes on ML & AI'
description:      'Notes on ML & AI'
url:              http://www.albertauyeung.com/
baseurl:          /

author:
  name:           'Albert Au Yeung'
  url:            http://www.albertauyeung.com/

plugins: [jekyll-paginate]
paginate:         5

# Custom vars
version:          2.1.0
